import { describe, it, expectTypeOf } from 'vitest';
import type { Resolve, And } from '../types';

describe('types', () => {
  describe('And', () => {
    it('And<[_], [_]>', () => expectTypeOf<And<[1], [2]>>().toEqualTypeOf<[1, 2]>());
    it('And<[_], [_?]>', () => expectTypeOf<And<[1], [2?]>>().toEqualTypeOf<[1, 2?]>());
    it('And<[_], _[]>', () => expectTypeOf<And<[1], 2[]>>().toEqualTypeOf<(1 | 2)[]>());
    it('And<[_?], [_]>', () => expectTypeOf<And<[1?], [2]>>().toEqualTypeOf<(1 | 2)[]>());
    it('And<[_?], [_?]>', () => expectTypeOf<And<[1?], [2?]>>().toEqualTypeOf<[1?, 2?]>());
    it('And<[_?], _[]>', () => expectTypeOf<And<[1?], 2[]>>().toEqualTypeOf<(1 | 2)[]>());
    it('And<_[], [_]>', () => expectTypeOf<And<1[], [2]>>().toEqualTypeOf<(1 | 2)[]>());
    it('And<_[], [_?]>', () => expectTypeOf<And<1[], [2?]>>().toEqualTypeOf<(1 | 2)[]>());
    it('And<_[], _[]>', () => expectTypeOf<And<1[], 2[]>>().toEqualTypeOf<(1 | 2)[]>());
  });
  describe('Union', () => {
    it('[_] | [_]', () => expectTypeOf<Resolve<[1] | [2]>>().toEqualTypeOf<[1 | 2]>());
    it('[_] | [_?]', () => expectTypeOf<Resolve<[1] | [2?]>>().toEqualTypeOf<[(1 | 2)?]>());
    it('[_] | _[]', () => expectTypeOf<Resolve<[1] | 2[]>>().toEqualTypeOf<(1 | 2)[]>());
    it('[_] | [_, _]', () => expectTypeOf<Resolve<[1] | [2, 3]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_] | [_, _?]', () => expectTypeOf<Resolve<[1] | [2, 3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_] | [_?, _?]', () => expectTypeOf<Resolve<[1] | [2?, 3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_] | (_ | _)[]', () => expectTypeOf<Resolve<[1] | (2 | 3)[]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_?] | [_]', () => expectTypeOf<Resolve<[1?] | [2]>>().toEqualTypeOf<[(1 | 2)?]>());
    it('[_?] | [_?]', () => expectTypeOf<Resolve<[1?] | [2?]>>().toEqualTypeOf<[(1 | 2)?]>());
    it('[_?] | _[]', () => expectTypeOf<Resolve<[1?] | 2[]>>().toEqualTypeOf<(1 | 2)[]>());
    it('[_?] | [_, _]', () => expectTypeOf<Resolve<[1?] | [2, 3]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_?] | [_, _?]', () => expectTypeOf<Resolve<[1?] | [2, 3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_?] | [_?, _?]', () => expectTypeOf<Resolve<[1?] | [2?, 3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_?] | (_ | _)[]', () => expectTypeOf<Resolve<[1?] | (2 | 3)[]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('_[] | [_]', () => expectTypeOf<Resolve<1[] | [2]>>().toEqualTypeOf<(1 | 2)[]>());
    it('_[] | [_?]', () => expectTypeOf<Resolve<1[] | [2?]>>().toEqualTypeOf<(1 | 2)[]>());
    it('_[] | _[]', () => expectTypeOf<Resolve<1[] | 2[]>>().toEqualTypeOf<(1 | 2)[]>());
    it('_[] | [_, _]', () => expectTypeOf<Resolve<1[] | [2, 3]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('_[] | [_, _?]', () => expectTypeOf<Resolve<1[] | [2, 3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('_[] | [_?, _?]', () => expectTypeOf<Resolve<1[] | [2?, 3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('_[] | (_ | _)[]', () => expectTypeOf<Resolve<1[] | (2 | 3)[]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_, _] | [_]', () => expectTypeOf<Resolve<[1, 2] | [3]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_, _] | [_?]', () => expectTypeOf<Resolve<[1, 2] | [3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_, _] | _[]', () => expectTypeOf<Resolve<[1, 2] | 3[]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_, _] | [_, _]', () => expectTypeOf<Resolve<[1, 2] | [3, 4]>>().toEqualTypeOf<[1 | 3, 2 | 4]>());
    it('[_, _] | [_, _?]', () => expectTypeOf<Resolve<[1, 2] | [3, 4?]>>().toEqualTypeOf<[(1 | 3), (2 | 4)?]>());
    it('[_, _] | [_?, _?]', () => expectTypeOf<Resolve<[1, 2] | [3?, 4?]>>().toEqualTypeOf<[(1 | 3)?, (2 | 4)?]>());
    it('[_, _] | (_ | _)[]', () => expectTypeOf<Resolve<[1, 2] | (3 | 4)[]>>().toEqualTypeOf<(1 | 2 | 3 | 4)[]>());
    it('[_, _?] | [_]', () => expectTypeOf<Resolve<[1, 2?] | [3]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_, _?] | [_?]', () => expectTypeOf<Resolve<[1, 2?] | [3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_, _?] | _[]', () => expectTypeOf<Resolve<[1, 2?] | 3[]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_, _?] | [_, _]', () => expectTypeOf<Resolve<[1, 2?] | [3, 4]>>().toEqualTypeOf<[(1 | 3), (2 | 4)?]>());
    it('[_, _?] | [_, _?]', () => expectTypeOf<Resolve<[1, 2?] | [3, 4?]>>().toEqualTypeOf<[(1 | 3), (2 | 4)?]>());
    it('[_, _?] | [_?, _?]', () => expectTypeOf<Resolve<[1, 2?] | [3?, 4?]>>().toEqualTypeOf<[(1 | 3)?, (2 | 4)?]>());
    it('[_, _?] | (_ | _)[]', () => expectTypeOf<Resolve<[1, 2?] | (3 | 4)[]>>().toEqualTypeOf<(1 | 2 | 3 | 4)[]>());
    it('[_?, _?] | [_]', () => expectTypeOf<Resolve<[1?, 2?] | [3]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_?, _?] | [_?]', () => expectTypeOf<Resolve<[1?, 2?] | [3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_?, _?] | _[]', () => expectTypeOf<Resolve<[1?, 2?] | 3[]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('[_?, _?] | [_, _]', () => expectTypeOf<Resolve<[1?, 2?] | [3, 4]>>().toEqualTypeOf<[(1 | 3)?, (2 | 4)?]>());
    it('[_?, _?] | [_, _?]', () => expectTypeOf<Resolve<[1?, 2?] | [3, 4?]>>().toEqualTypeOf<[(1 | 3)?, (2 | 4)?]>());
    it('[_?, _?] | [_?, _?]', () => expectTypeOf<Resolve<[1?, 2?] | [3?, 4?]>>().toEqualTypeOf<[(1 | 3)?, (2 | 4)?]>());
    it('[_?, _?] | (_ | _)[]', () => expectTypeOf<Resolve<[1?, 2?] | (3 | 4)[]>>().toEqualTypeOf<(1 | 2 | 3 | 4)[]>());
    it('(_ | _)[] | [_]', () => expectTypeOf<Resolve<(1 | 2)[] | [3]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('(_ | _)[] | [_?]', () => expectTypeOf<Resolve<(1 | 2)[] | [3?]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('(_ | _)[] | _[]', () => expectTypeOf<Resolve<(1 | 2)[] | 3[]>>().toEqualTypeOf<(1 | 2 | 3)[]>());
    it('(_ | _)[] | [_, _]', () => expectTypeOf<Resolve<(1 | 2)[] | [3, 4]>>().toEqualTypeOf<(1 | 3 | 2 | 4)[]>());
    it('(_ | _)[] | [_, _?]', () => expectTypeOf<Resolve<(1 | 2)[] | [3, 4?]>>().toEqualTypeOf<(1 | 2 | 3 | 4)[]>());
    it('(_ | _)[] | [_?, _?]', () => expectTypeOf<Resolve<(1 | 2)[] | [3?, 4?]>>().toEqualTypeOf<(1 | 2 | 3 | 4)[]>());
    it('(_ | _)[] | (_ | _)[]', () => expectTypeOf<Resolve<(1 | 2)[] | (3 | 4)[]>>().toEqualTypeOf<(1 | 2 | 3 | 4)[]>());
  });
});